package com.lea.stamp.data.db

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "user_info")
data class UserInfoEntity(
    @PrimaryKey
    val id: Int = 0, // Singleton row
    val age: Int,
    val sex: String,
    val height: Float,
    val weight: Float,
    val activityLevel: String,
    val healthConditions: String, // Comma separated
    val dietaryPattern: String,
    val medications: String,
    val primaryGoal: String,
    val goalIntensity: String,
    val secondaryGoals: String, // Comma separated
    val detailGoal: String = "" // Generated by AI
)
